package utils.resources;

public enum ImageIdentifier {
    MENU_BACKGROUND,
    GAME_BACKGROUND,
    LOGO,
    HELP,
    PAUSE_ICON,
    AMBASSADOR,
    ASSSASSIN,
    CAPTAIN,
    CONTESSA,
    DUKE,
    CARDBACK_VERTICAL_UTD,
    CARDBACK_HORIZONTAL_LTR,
    CARDBACK_HORIZONTAL_RTL
}